### ISSUE TITLE
Rewrite to TypeScript

### ISSUE THREAD

**Issue by gxrsti** [Would-You-Bot/would-you#175]
Type safety, better maintainability, build checks and more...

**Comment by mezotv** [comment]
Good luck on this!

**Comment by rustytrim** [comment]
Hey @gxrsti would it be okay if I assisted you in converting the code to ts or do you want to do this alone.

**Comment by gxrsti** [comment]
Hey @rtgamingwdt, I've made good progress on the rewrite. I would like to handle the basic structure by myself, but if I need your help with anything specific, I'll let you know!

**Comment by rustytrim** [comment]
Okay thanks!

**Comment by gxrsti** [comment]
@rtgamingwdt If you want you can help remove all the `any` types remaining in the code

**Comment by rustytrim** [comment]
Okay that sounds good, I am currently at school though so I will have to start working on it a little bit later

**Comment by gxrsti** [comment]
Sure, no rush. We'll need to test the entire code before merging which will take some time :)

**Comment by gxrsti** [comment]
Rewrite is done, this can be closed.
