### ISSUE TITLE
Add Issue and PR template

### ISSUE THREAD

**Issue by Shikhar-Raj78** [Would-You-Bot/would-you#181]
Add an issue and pr template so contributors are required to follow a predefined style for their pull requests and issues.

**Comment by Shikhar-Raj78** [comment]
hi @mezotv, can you assign this issue under hacktoberfest 2023.

**Comment by mezotv** [comment]
> hi @mezotv, can you assign this issue under hacktoberfest 2023.  

Sure but you already made a pull request for this.

**Comment by Shikhar-Raj78** [comment]
@mezotv Yes i have made the PR. Is there an issue? 
I am new to Open source, that why i am asking.

**Comment by mezotv** [comment]
> @mezotv Yes i have made the PR. Is there an issue? 
> I am new to Open source, that why i am asking.

Nah all good but usually people make an issue first.

**Comment by Shikhar-Raj78** [comment]
@mezotv can you please review my PR. Also if possible, can you please add hacktoberfest add on this issue

**Comment by mezotv** [comment]
> @mezotv can you please review my PR. Also if possible, can you please add hacktoberfest add on this issue

The tag isnt needed on the issue itself only on the repo tho I added it!
