### ISSUE TITLE
Cooldown bug - buttons are not interactable, Inaccurate time.

### ISSUE THREAD

**Issue by TzurS11** [Would-You-Bot/would-you#88]
When pressing on a button to generate a new question. it will generate new question but if you have a cooldown. you can't interact with the buttons (not talking about new question button). 

just watch the video if you don't understand or you want to see how to reproduce the bug:
https://streamable.com/6yxv1r

if we already talk about the cooldown issue. cooldown message will show the time 30 seconds from now instead when the time is actually up.

mozo is already aware of those bugs. but if anyone else is willing to fix those issues. have fun :)

**Comment by mezotv** [comment]
Fixed in the most recent version. Thanks for pointing this out!
